language: python
python:
  - "3.10"
  - "3.11"
# TODO: pylint ruamel.yaml doesn't work on travis with this version  - "3.5"
# TODO: pylint ruamel.yaml doesn't work on travis with this version  - "3.5-dev"
before_install:
 - bundle install
install: "pip install ruamel.yaml flake8 pylint"
script: "rake test"
