name: Github Actions
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.10'
          - '3.11'
        ruby-version:
          - '3.1'
          - '3.2'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: |
          gem install bundler
          gem update bundler
          bundle install --jobs 4 --retry 3
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      - uses: actions/checkout@v2
      - run: pip install ruamel.yaml flake8 pylint
      - name: 'Run tests'
        run: bundle exec rake test
